import torch
from torch.utils.data import Dataset, DataLoader, random_split
import pandas
from typing import Union, Tuple
import os

class MordredDataset(Dataset):
    # Class to load descriptors and labels from a preprocessed csv
    # generated by mordred
    def __init__(self, data_csv: Union[str, os.PathLike],
            label_col: str = 'Solubility',
            id_col: str = 'ID'):
        super().__init__()
        self.mordred_df = pd.read_csv(data_csv)
        self.label_col = label_col
        self.id_col = id_col

    def __len__(self):
        return len(self.mordred_df)

    def __getitem__(self, idx: int) -> Tuple[str, torch.Tensor, torch.Tensor]:
        data_row = self.mordred_df.loc[idx].tolist()
        data_id = data_row.pop(0)
        data_label = torch.tensor(data_row.pop(0))
        data_row = torch.tensor(data_row)
        return(data_id, data_row, data_label)
